### ISSUE TITLE
Source for lexer isn't being generated with V1.3.1

### ISSUE THREAD

**Issue by larrymelia** [julianthome/inmemantlr#11]
For some reason, the lexer isn't being generated in V1.3.1. Any ideas? Also, the Eclipse compiler isn't being brought in for some reason via your POM reference. So I had to add it to the build.
(See https://github.com/cyberthinkers/typescript-to-scala-js-facade - it's a work in progress.) 

Exception in thread "main" java.lang.IllegalArgumentException: bytecode of class GenScalaFacadesFromTypescriptLexer is empty
	at org.snt.inmemantlr.comp.SpecialJavaFileManager.getByteCodeFromClass(SpecialJavaFileManager.java:99)
	at org.snt.inmemantlr.comp.StringCompiler.compile(StringCompiler.java:135)
	at org.snt.inmemantlr.GenericParser.compile(GenericParser.java:293)
	at com.cyberthinkers.tools.GenScala$.parseSource(GenScalaFacadesFromTypescriptBaseListenerScala.scala:35)
	at com.cyberthinkers.tools.GenScala$.main(GenScalaFacadesFromTypescriptBaseListenerScala.scala:27)
	at com.cyberthinkers.tools.GenScala.main(GenScalaFacadesFromTypescriptBaseListenerScala.scala)

**Comment by julianthome** [comment]
Dear Larry,

I have split the answer into two parts:

**1. The dependency issue:**
Due to dependency reasons, I had to split the inmemantlr package into two modules `inmemantr-api ` and `inmemantr-tool`--the `inmemantlr-tool` package has to be self-contained because it is the standalone tool whereas the `inmemantlr-api` package contains the API and does not have to be self-contained. However, please use the `inmemantlr-api` package v1.3.1 or v1.3.2:

```bash
"com.github.julianthome"          % "inmemantlr-api"        % "1.3.2",
```

**2. The lexer issue:**
The problem that you have described is essentially the same as in #10. I have re-checked with the latest vanilla ANTLR release and by performing the steps down below, the error is exactly the same as the one that you've described. For reproducing the problem, you could execute the following commands in your console. 

```bash
cd /tmp
sudo curl -O http://www.antlr.org/download/antlr-4.6-complete.jar
export CLASSPATH=".:/tmp/antlr-4.6-complete.jar:$CLASSPATH"
alias antlr4='java -jar /tmp/antlr-4.6-complete.jar'
antlr4 GenScalaFacadesFromTypescript.g4
javac -classpath '/tmp/antlr-4.6-complete.jar:.' *.java
```

``` bash
GenScalaFacadesFromTypescriptLexer.java:156: error: cannot find symbol
			return !strictMode;
			        ^
  symbol:   variable strictMode
  location: class GenScalaFacadesFromTypescriptLexer
1 error
```

The problem is still in the strict mode property of the grammar with which ANTLR seems to have a problem as described above. The Java compiler from inmemantlr returns the same problem and cannot generate the bytecode due to this issue. 

For solving the problem, I would suggest to have a look at the  [ECMA script grammar](https://github.com/antlr/grammars-v4/tree/master/ecmascript) from the `grammars-v4` package which might be a useful resource since they also use the strict member of the Lexer class. Please note that all of the grammars-v4 grammars are added to inmemantlr as test-cases and before I make a new release, I always make sure that inmemantlr works properly on all of them. The grammars-v4 cases are handled by the JUnit class [TestExternalGrammars](https://github.com/julianthome/inmemantlr/blob/master/inmemantlr-api/src/test/java/TestExternalGrammars.java) (the ECMA script test case can be found in the function `testEcmaScript`).

Kind regards,
  Julian

**Comment by larrymelia** [comment]
I guess I can create a strictMode variable, but I don't understand why the
Antlr4 generator isn't creating it if it's undefined. Only the ECMA script
grammar seems to define the strict variable in several places. I'm not sure
what I did because it seems it seem to compile correctly after the last
update to the most recent version of Antlr4 (where the undefined strict
variable was supposedly fixed). Finally, I had to add this to the SBT build:

"org.eclipse.jdt.core.compiler" % "ecj" % "4.6.1",

to get it to work. I'm not sure why your POM's aren't pulling it in as part
of your library.

I'm using 1.3.1 of your library and I'll switch to 1.3.2 when I get home
from work.
(FYI- I'm in Seattle, WA in the US.)

Finally, with version 1.3 I was getting the "missing strict variable" error
message, but now, with 1.3.1, it just says that it can't find the lexer. If
you're catching the compiler error, you might want to throw it again so at
least the underlying problem will show up.

Thanks, Julian, for all your help and I'll be plugging at it again tonight.


PS-After I get this fixed, I'll share with you my approach to creating a
reduced or minimal AST from the AST your library creates. I'm sure you'll
find it interesting.

**Comment by julianthome** [comment]
Hello Larry,

did you use the most recent version of the ANTLR github repo or the one from maven central?

Regarding, the Java compiler error--I will change the code according to your suggestion. 

Thank you very much and kind regards, 
  Julian

**Comment by larrymelia** [comment]
Hi Julian,

I put this block of code in my grammar (see below) and it seems to be
working.However, the ANTL4 "missing strictMode" bug, which was reported
about a year ago, still seems to be broken, evidently. Thank you for being
very cordial and all your help!

Larry

------------------------------------------------------------
--------------------------------------

grammar GenScalaFacadesFromTypescript;

@lexer::members {
    private boolean strictMode = true;
    /**
     * Returns {@code true} iff the lexer operates in strict mode.
     *
     * @return {@code true} iff the lexer operates in strict mode.
     */
    public boolean getStrictMode() {
        return this.strictMode;
    }
}
