### ISSUE TITLE
ast.toDot() not output correctly

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#13]
ast.toDot() not output correctly

```
File f = new File("/Users/peter/Desktop/Hello.g4");
GenericParser gp = new GenericParser(f);
DefaultTreeListener dlist = new DefaultTreeListener();

gp.setListener(dlist);
gp.compile();
Ast ast = dlist.getAst();
System.out.println(ast.toDot());
```

```
grammar Hello;
r   : 'hello' ID;
ID  : [a-z]+ ;
WS  : [ \t\r\n]+ -> skip ;
```

Wrong output:
```
graph {
	node [fontname=Helvetica,fontsize=11];
	edge [fontname=Helvetica,fontsize=10];
	n0 [label="(0)\nroot\nroot"];
}
```

**Comment by julianthome** [comment]
Hi Peter, 
in the code above, you've just created a `GenericParser` but you did not actually parse a string which is the reason why there is an AST with only a root node.
Best,
  Julian

**Comment by mcheung63** [comment]
Thanks Julian, i was confusing myself. I thought AST can be generate just by g4 file, no need to parse anything.

**Comment by mcheung63** [comment]
The dot graph output still not correct, please help

**Comment by mcheung63** [comment]
sorry it works.

**Comment by julianthome** [comment]
B.T.W. for getting the AST of the grammar you could create a `GenericParser` from the antlr4 grammar provided by the grammars-v4 antlr4 grammar (https://github.com/teverett/grammars-v4/tree/master/antlr4) which can then be used in order to parse the `g4` files you are interested in. The antlr4 JUnit test case (https://github.com/teverett/grammars-v4/blob/master/_grammar-test/src/test/java/TestAntlr4.java) illustrates how to make the Antlr grammar work with inmemantlr.

**Comment by mcheung63** [comment]
thanks for your helps gentleman
