### ISSUE TITLE
1.3.8 from maven central has no AstSerializer

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#14]
1.3.8 from maven central has no AstSerializer class

<img width="2002" alt="2017-07-30 11 47 26" src="https://user-images.githubusercontent.com/1779905/28754916-8dc0a400-7581-11e7-9b51-47faec3de683.png">

**Comment by julianthome** [comment]
Yes, that is true. I've just added the `AstSerializer` because I wanted to add support for JSON and XML serialization. I just wanted to show you an example how you can actually modify the dot serialization. I will however, add the `AstSerializer` with the next inmemantlr realease -- I am not completely done with the feature implementation yet and need to add some test cases before doing release 1.3.9 (which will be done in a week). So for the time being, I would suggest that you implement (or copy) the current `AstSerializer` implementation. 

Best,
  Julian
