### ISSUE TITLE
Netbeans integration

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#15]
Dear, i am integrating it into netbeans, but netbeans has build in antlr 4.5.3 so it crashed with inmemantlr. I tried to add antlr 4.7 dependency in pom but still fail. Is there any inmemantlr version that support antlr 4.5.3? Thanks

**ANTLR Tool version 4.5.3 used for code generation does not match the current runtime version** 4.7org.snt.inmemantlr.exceptions.CompilationErrorException: ----------
1. ERROR in /CalculatorLexer.java (at line 2)
	import org.antlr.v4.runtime.Lexer;
	       ^^^^^^^^^
The import org.antlr cannot be resolved

**Comment by julianthome** [comment]
Hello Peter,
this looks like a maven dependency conflict.
There are some useful blogposts with suggestions how to solve this issue.
 (https://stackoverflow.com/questions/19659425/conflicting-library-version-in-a-java-maven-project, http://techidiocy.com/maven-dependency-version-conflict-problem-and-resolution).  

The first version of inmemantlr 1.2 was using antlr 4.5.3 but I would not suggest to use it because a lot of things have changed since then. Furhtermore, I cannot garantee that the old version works for all the grammars-v4 grammars. Instead of using the old version of inmemantlr, I think it might be a better idea to try to fix the maven dependency conflict. 

Best wishes and kind regards,
  Julian
