### ISSUE TITLE
Compile fail

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#16]
Hi, i got a compile fail, any hints?
<img width="1948" alt="2017-08-13 9 58 30" src="https://user-images.githubusercontent.com/1779905/29250283-bf5c95e0-8072-11e7-8967-827265d2f7fd.png">

**Comment by julianthome** [comment]
Dear Peter,
since you are running `mvn clean install`, which implicitly invokes `mvn validate` (https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html), the gpg plugin is invoked. However, this plugin is only important when releasing the plugin on Maven central. A quickfix is to simply comment out the `mvn-gpg-plugin` in the `pom.xml`.

Actually, I just did that ;-) and pushed the change, so a simple `git pull` should suffice. 

Best,
  Julian
