### ISSUE TITLE
which antlr version

### ISSUE THREAD

**Issue by mcheung63** [julianthome/inmemantlr#17]
Hi, when calling StringCompiler::compile() to compile the g4 file, which antlr.jar it use for compilation? I tried to print out the "cp" variable but nothing.

		List<String> optionList = new ArrayList<>();
		System.out.println(StringUtils.join(cp));
		optionList.addAll(cp);
		optionList.add("-source");
		optionList.add("1.7");

Thanks
from Peter

**Comment by julianthome** [comment]
Hi Peter,
inmemantlr is based on the latest antlr version 4.7 (https://github.com/julianthome/inmemantlr/blob/master/pom.xml).

Best wishes and kind regards,
  Julian

**Comment by mcheung63** [comment]
May i know which line is compiling the g4 file into java files? I am still trying to port it into netbeans plugin. Thanks

**Comment by julianthome** [comment]
Hi Peter,

unfortunately, there is not a single line to which I could point you to, because `.g4` files cannot be compiled directly which is the reason why I developed `inmemantlr` in the first place. antlr generates `.java` files for the parsers and lexers defined in the `.g4` file. `inmemantlr` takes those classes and compiles them in-memory by means of `inmemantlr's` `StringComiler` class. However, there are a lot of things which have to be done beforehand (e.g. loading the token vocabulary, creating classes in the right order to ensure that dependencies are met, adding utility files, etc.).

If you cannot use `inmemantlr`, you could take a look at the official IntelliJ plugin (https://github.com/antlr/intellij-plugin-v4)  which might be a better resource for your use case. Since, you are developing an IDE plugin, you can expect a file system to be present so that you could actually use antlr directly (without in-memory compilation), anyway. Otherwise, in case you still like to use `inmemantlr`, I would suggest using it right-away (with antlr 4.7) because quite some functionalities have been added and some bugs have been fixed since the last release (https://github.com/antlr/antlr4/releases). For dealing with the version conflict, I would suggest looking at http://techidiocy.com/maven-dependency-version-conflict-problem-and-resolution/.

BTW.: Please do not create a github-issue for problems which are not related to potential bugs or missing features. Instead, you could directly drop me en E-mail; the address can be found on my github page.

Best wishes and kind regards,
  Julian

**Comment by mcheung63** [comment]
thanks a lot
